name: System Pop Art Final Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
      - name: Beam to Google Drive
        if: success()
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: bin/*.apk
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}  
          
